variable "name_tag" {}
variable "my_vpc_id" {}
variable "environment" {}
variable "availability_zone_a" {}
variable "availability_zone_b" {}
variable "subnet_cidr_block_public_a" {}
variable "subnet_cidr_block_public_b" {}
variable "subnet_cidr_block_private_a" {}
variable "subnet_cidr_block_private_b" {}
variable "subnet_cidr_block_private_a2" {}
variable "subnet_cidr_block_private_b2" {}
variable "subnet_cidr_block_private_a3" {}
variable "subnet_cidr_block_private_b3" {}